image: yasu31/srl:mobilerack-env
before_script:
  - sudo apt-get install -y wget
  - wget https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz
  - sudo tar -xvzf drake-latest-focal.tar.gz -C /opt
  - sudo /opt/drake/share/drake/setup/install_prereqs
variables:
  GIT_SUBMODULE_STRATEGY: recursive
build:
  script:
    - cmake -DCMAKE_PREFIX_PATH=/opt/drake .
    - make
