<?xml version="1.0"?>

<!--
this file defines the xacro macros that can be used to create PCC augmented models
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
  <material name="green">
    <color rgba="0.2 1 0.2 0.8"/>
  </material>
  <material name="white">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

  <xacro:property name="PI" value="3.1415" />
  <xacro:macro name="ball-joint" params="id parent child">
    <!--creates a (pseudo) ball joint, called from the PCC macro..-->
    <joint name="${id}-ball-joint_x_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${id}-ball-joint_link_0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-PI/2}" upper="${PI/2}" effort="1000" velocity="1000"/>
    </joint>
    <link name="${id}-ball-joint_link_0">
      <xacro:default_inertial/>
    </link>
    <joint name="${id}-ball-joint_y_joint" type="revolute">
      <parent link="${id}-ball-joint_link_0"/>
      <child link="${id}-ball-joint_link_1"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-PI/2}" upper="${PI/2}" effort="1000" velocity="1000"/>
    </joint>
    <link name="${id}-ball-joint_link_1">
      <xacro:default_inertial/>
   </link>
    <joint name="${id}-ball-joint_z_joint" type="revolute">
      <parent link="${id}-ball-joint_link_1"/>
      <child link="${child}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-PI/2}" upper="${PI/2}" effort="1000" velocity="1000"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="default_inertial">
    <!--since the RBDL needs a inertial info for each link, just assign a really small value to links where we don't have to consider inertia.-->
    <inertial>
      <mass value="0.00001"/>
      <inertia ixx="0.00001" ixy="0.0000" ixz="0.0000" iyy="0.00001" iyz="0.0000" izz="0.00001"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="PCC" params="id parent child length mass radius:=0.02">
    <!--creates a PCC piece-->
    <xacro:ball-joint id="${id}-ball" parent="${parent}" child="${id}-a"/>
    <link name="${id}-a">
      <xacro:default_inertial/>
    </link>
    <joint name="${id}-a-b_joint" type="prismatic">
      <parent link="${id}-a"/>
      <child link="${id}-b"/>
      <axis xyz="0 0 -1"/>
      <origin xyz="0 0 ${length/2}"/>
      <limit lower="0" upper="${length/2}" effort="1000" velocity="1000"/>
    </joint>
    <link name="${id}-b">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <!-- <origin xyz="0 0 ${length/2}"/> -->
        <material name="green"/>
      </visual>
      <visual>
        <!-- this marks the +x direction (i.e. the direction where the first chamber should be) -->
        <geometry>
          <box size="${radius/5.} ${radius/5.} ${radius/5.}"/>
        </geometry>
        <origin xyz="${radius} 0 0"/>
        <material name="white"/>
      </visual>
      <inertial>
        <mass value="${mass}"/>
        <!-- moment of inertia for a cylinder with radius and length -->
        <inertia ixx="${mass * (3*radius**2 + length**2) / 12.}" ixy="0.000" ixz="0.000" iyy="${mass * (3*radius**2 + length**2) / 12.}" iyz="0.000" izz="${mass * radius*radius / 2.}"/>
      </inertial>
    </link>
    <joint name="${id}-b-${child}_joint" type="prismatic">
      <parent link="${id}-b"/>
      <child link="${child}"/>
      <axis xyz="0 0 -1"/>
      <origin xyz="0 0 ${length/2}"/>
      <limit lower="0" upper="${length/2}" effort="1000" velocity="1000"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="empty_link" params="name">
    <link name="${name}">
      <xacro:default_inertial/>
    </link>
  </xacro:macro>

  <xacro:macro name="rigid_rotation" params="rotX rotY rotZ parent child">
    <joint name="${parent}_${child}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin rpy="${rotX} ${rotY} ${rotZ}"/>
    </joint>
  </xacro:macro>
</robot>
